-- Recurring series, and the budget columns the engine needs.
--
-- Rent, salary, subscriptions, utilities and insurance are the skeleton of a
-- household's month. A detected series is what lets safe-to-spend subtract the
-- rent that has not been charged yet instead of pretending the money is there
-- (spec §18, §32).
--
-- A series is the *pattern*. `app.obligations` holds the individual claims it
-- generates, which is why obligations gain a link back here rather than being
-- replaced: an obligation can be settled by a transaction, and a pattern cannot.

create type app.recurrence_frequency as enum (
  'weekly',
  'biweekly',
  -- Not a rounding of biweekly. Panamanian salaries are paid on the 15th and the
  -- last day of the month: 24 payments a year on two fixed calendar days, not 26
  -- every fourteen days. Collapsing them invents a paycheck (spec §32).
  'semimonthly',
  'monthly',
  'quarterly',
  'annual'
);

create table app.recurring_series (
  id             uuid primary key default public.uuid_generate_v7(),
  household_id   uuid not null references app.households (id) on delete cascade,
  merchant_id    uuid references app.merchants (id) on delete set null,
  category_id    uuid references app.categories (id) on delete set null,
  account_id     uuid references app.accounts (id) on delete set null,
  owner_id       uuid references app.profiles (id) on delete set null,

  name           text not null,
  direction      app.transaction_direction not null default 'outflow',
  scope          app.financial_scope not null default 'household',

  -- The typical amount: a median, so one unusual month does not move it.
  expected_amount numeric(19, 4) not null check (expected_amount >= 0),
  currency       char(3) not null default 'USD' references platform.currencies (code),

  frequency      app.recurrence_frequency not null,
  -- The calendar days a semimonthly series lands on, 31 meaning month end.
  -- Carried here so projecting the series forward needs nothing else: a salary
  -- paid on the 5th and the 20th must not be projected onto the 15th and 31st.
  anchor_days    smallint[],

  last_seen_on   date not null,
  next_expected_date date not null,

  confidence     numeric(4, 3) not null check (confidence between 0 and 1),
  -- How much the amounts vary around the median. A utility swings month to month
  -- and is still plainly recurring, so this informs the band, not the verdict.
  amount_variation numeric(6, 4) not null default 0 check (amount_variation >= 0),
  occurrence_count integer not null check (occurrence_count >= 3),

  is_essential   boolean not null default true,
  is_active      boolean not null default true,

  detected_by    app.provenance not null default 'system',
  confirmed_by   uuid references app.profiles (id) on delete set null,
  confirmed_at   timestamptz,

  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  deleted_at     timestamptz,

  -- Anchor days belong to the one cadence that is defined by calendar days.
  constraint recurring_series_anchors_are_semimonthly
    check (anchor_days is null or frequency = 'semimonthly'),

  constraint recurring_series_moves_forward
    check (next_expected_date > last_seen_on)
);

create index recurring_series_household_idx
  on app.recurring_series (household_id, next_expected_date)
  where is_active and deleted_at is null;

create index recurring_series_merchant_idx
  on app.recurring_series (household_id, merchant_id)
  where deleted_at is null;

create trigger recurring_series_set_updated_at
  before update on app.recurring_series
  for each row execute function public.set_updated_at();

-- An obligation is one claim generated by a pattern. Nullable because a
-- household may also enter a one-off claim by hand, which belongs to no series.
alter table app.obligations
  add column series_id uuid references app.recurring_series (id) on delete set null;

create index obligations_series_idx on app.obligations (series_id)
  where series_id is not null;

-- What a rolling budget line carried in from the period before. Stored rather
-- than recomputed: the rollover a household saw when it made a decision is the
-- rollover that must still be there afterwards.
alter table app.budget_lines
  add column rollover_in numeric(19, 4) not null default 0;

-- ---------------------------------------------------------------------------
-- Row-level security
-- ---------------------------------------------------------------------------

alter table app.recurring_series enable row level security;
alter table app.recurring_series force row level security;

create policy recurring_series_household_access on app.recurring_series
  for all to authenticated
  using (app.is_household_member(household_id))
  with check (app.is_household_member(household_id));

grant select, insert, update, delete on app.recurring_series to authenticated;

update platform.schema_version
   set version = 7,
       description = 'Phase 7 — recurring series, budget rollover',
       applied_at = now()
 where id;
